package dto

type BehaviorItem struct {
	BpitId              string `json:"bpit_id"`
	Workcode            string `json:"workcode"`
	Name                string `json:"name"`
	Trd                 string `json:"trd"`
	Lid                 string `json:"lid"`
	Leaderid            string `json:"leaderid"`
	Avgtrd              string `json:"avgtrd"`
	Avglid              string `json:"avglid"`
	Model               string `json:"model"`
	Hero                string `json:"hero"`
	WeeklySubmitRate    string `json:"weekly_submit_rate"`
	WeeklySubmitRateAvg string `json:"weekly_submit_rate_avg"`
	Zbhyd               string `json:"zbhyd"`
	ZbhydAvg            string `json:"zbhyd_avg"`
	WeeklySubmitRateDbz string `json:"weekly_submit_rate_dbz"`
	ZbhydDbz            string `json:"zbhyd_dbz"`
	TrdDbz              string `json:"trd_dbz"`
	LjdDbz              string `json:"ljd_dbz"`
	JsMonth             string `json:"js_month"`
	Dt                  string `json:"dt"`
}


type OrgItem struct {
	BpitID                int     `json:"bpit_id"`
	ZzbID                 string  `json:"zzb_id"`
	ZzbName               string  `json:"zzb_name"`
	Zzrs                  int     `json:"zzrs"`
	OkrsyName             string  `json:"okrsy_name"`
	OkrsyIsCommit         float64 `json:"okrsy_is_commit"`
	OkrsyDbl              float64 `json:"okrsy_dbl"`
	OkrsyPjIsCommit       float64 `json:"okrsy_pj_is_commit"`
	OkrsyPjDbl            float64 `json:"okrsy_pj_dbl"`
	OkrsyIsCommitDbz      float64 `json:"okrsy_is_commit_dbz"`
	OkrsyDblDbz           float64 `json:"okrsy_dbl_dbz"`
	TrdMonth              float64 `json:"trd_month"`
	Trd_N_1_Month         float64 `json:"trd_n_1_month"`
	TrdPjMonth            float64 `json:"trd_pj_month"`
	TrdDbMonth            float64 `json:"trd_db_month"`
	TrdMonthPjDbj         float64 `json:"trd_month_pj_dbj"`
	TrdMonthDbDbj         float64 `json:"trd_month_db_dbj"`
	LjdMonth              float64 `json:"ljd_month"`
	Ljd_N_1_Month         float64 `json:"ljd_n_1_month"`
	LjdPjMonth            float64 `json:"ljd_pj_month"`
	LjdDbMonth            float64 `json:"ljd_db_month"`
	LjdMonthPjDbj         float64 `json:"ljd_month_pj_dbj"`
	LjdMonthDbDbj         float64 `json:"ljd_month_db_dbj"`
	SalzlMonth            float64 `json:"salzl_month"`
	Lzl_3zjMonth          float64 `json:"lzl_3zj_month"`
	TrdMonthSum           float64 `json:"trd_month_sum"`
	Trd_N_1_MonthSum      float64 `json:"trd_n_1_month_sum"`
	TrdPjMonthSum         float64 `json:"trd_pj_month_sum"`
	TrdDbMonthSum         float64 `json:"trd_db_month_sum"`
	TrdMonthSumPjDbj      float64 `json:"trd_month_sum_pj_dbj"`
	TrdMonthSumDbDbj      float64 `json:"trd_month_sum_db_dbj"`
	LjdMonthSum           float64 `json:"ljd_month_sum"`
	Ljd_N_1_MonthSum      float64 `json:"ljd_n_1_month_sum"`
	LjdPjMonthSum         float64 `json:"ljd_pj_month_sum"`
	LjdDbMonthSum         float64 `json:"ljd_db_month_sum"`
	LjdMonthSumPjDbj      float64 `json:"ljd_month_sum_pj_dbj"`
	LjdMonthSumDbDbj      float64 `json:"ljd_month_sum_db_dbj"`
	SalzlMonthSum         float64 `json:"salzl_month_sum"`
	Lzl_3zjMonthSum       float64 `json:"lzl_3zj_month_sum"`
	JspstglMonth          float64 `json:"jspstgl_month"`
	Jyd                   float64 `json:"jyd"`
	Myd                   float64 `json:"myd"`
	JydJt                 float64 `json:"jyd_jt"`
	MydJt                 float64 `json:"myd_jt"`
	JsFz                  float64 `json:"js_fz"`
	JsFm                  float64 `json:"js_fm"`
	Jspstgl               float64 `json:"jspstgl"`
	JspstglPjdbz          float64 `json:"jspstgl_pjdbz"`
	JydDbz                float64 `json:"jyd_dbz"`
	MydDbz                float64 `json:"myd_dbz"`
	L_3zjlzlPj            float64 `json:"l_3zjlzl_pj"`
	SalzlPjMonthSum       float64 `json:"salzl_pj_month_sum"`
	L_3zjlzlPjMonthSum    float64 `json:"l_3zjlzl_pj_month_sum"`
	Fy22QnBzsyjd          float64 `json:"fy22_qn_bzsyjd"`
	Fy22QngzlRgcbsyjd     float64 `json:"fy22_qngzl_rgcbsyjd"`
	MonthRzryCrzcsxzb     float64 `json:"month_rzry_crzcsxzb"`
	Fy22QnBzsyjdJt        float64 `json:"fy22_qn_bzsyjd_jt"`
	Fy22QngzlRgcbsyjdJt   float64 `json:"fy22_qngzl_rgcbsyjd_jt"`
	MonthRzryCrzcsxzbJt   float64 `json:"month_rzry_crzcsxzb_jt"`
	SalzlPjDbj            float64 `json:"salzl_pj_dbj"`
	L_3zjlzlPjDbj         float64 `json:"l_3zjlzl_pj_dbj"`
	SalzlPjMonthSumDbz    float64 `json:"salzl_pj_month_sum_dbz"`
	L_3zjlzlPjMonthSumDbz float64 `json:"l_3zjlzl_pj_month_sum_dbz"`
	JsMonth               string  `json:"js_month"`
	Version               string  `json:"version"`
	Dt                    string  `json:"dt"`
}